apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo
        role: db
        environment: testing
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          resources:
            requests:
              cpu: 100m
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
        - name: mongo-sidecar
          resources:
            requests:
              cpu: 10m
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "service=mongo,environment=testing"
      volumes:
        - name: mongodb
          hostpath:
            path: /data/mongodb
            type: DirectoryOrCreate
