---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-many
  labels:
    app: influxdb
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
